### ISSUE TITLE
Set up end-to-end tests?

### ISSUE THREAD

**Issue by flaurida** [Airtable/blocks-name-quiz#2]
Hi there 👋I didn't find any end-to-end tests in `blocks-name-quiz`. I maintain an [open source library](https://github.com/qawolf/qawolf) that creates Playwright/Jest tests and runs them in CI.

Would you like me to set up end-to-end tests on this project? If you'd rather I add tests to a different project that's fine too!

**Comment by minicat** [comment]
Hi @flaurida - we're not looking to set up end-to-end tests for this project right now, but appreciate the offer. thank you!
